@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Ext(client, "API Client", "HTTP", "External client")

Container_Boundary(mvc_app, "MVC-example Application") {
    Boundary(controller_layer, "Controller Layer") {
        Component(controller, "Controller", "Web API Controller", "Processes HTTP requests, extracts parameters from requests. Used to implement the loose coupling between interface and logic layers")
    }
    Boundary(model_layer, "Model Layer") {
        Component(model, "Model", "", "Stores business logic and logic of working with entities, works directly with the database. Essentially the core of the application")
    }
    Boundary(view_layer, "View Layer") {
        Component(view, "View", "", "UI. Renders content based on data from the model. Users see and work directly with the view")
    }

    Rel_D(client, controller, "1. Some request triggered by a user action", "HTTP")
    BiRel(controller, model, "2. Geting data based on the request and its parameters")
    BiRel(controller, view, "3. Rendering content based on recieving data from model")
    Rel_U(controller, client, "4. Return rendered content to the client")

}
@enduml
